/* This file is autogenerated, do not edit*/
#include "moc_cmenu.cpp"
#include "moc_qevent_adapter.cpp"
#include "moc_qt_mainwindow.cpp"
#include "moc_qt_osgwidget.cpp"
#include "moc_qt_osgwidget2d.cpp"
